package cookingRecipe;

public class recipeList {
	public Object[] mixing = {
			"Afternoon Tea Set",
			"Apple Juice",
			"Assorted Fruits",
			"Assorted Sashimi",
			"Assorted Sashimi Bibimbap",
			"Bacon and Potato Dog Food",
			"Bacon Burger",
			"Belvast Eel Rice Bowl",
			"Birthday Cake",
			"Blueberry Whipped Cream Crepe",
			"BnR",
			"Brifne Rocks",
			"Cacao Chocolate Cake",
			"Cafe Mocha",
			"Camellia Sling",
			"Cappuccino",
			"Catfish Garden Salad",
			"Caviar Canape",
			"Caviar Salad",
			"Celery Salad",
			"Cheeseburger",
			"Chicken Burger",
			"Chocolate Crepe Cake",
			"Chocolate Milk",
			"Club Sandwich",
			"Coleslaw",
			"Cookies and Cream Cake",
			"Corned Abb Neagh Carp and Vegetables",
			"Crepe Cake",
			"Dog Biscuit",
			"Ebi Sushi",
			"Egg Caviar",
			"Egg Salad",
			"Egg Sandwich",
			"Espresso Macchiato",
			"Filia Cookie Set",
			"Fruit Salad",
			"Granita",
			"Halloween Wrapped Candy",
			"Halloween Wrapped Cookie",
			"Happy Dessert Time Combo",
			"Hard Cider",
			"Herb Mushroom Salad",
			"Highball",
			"Holiday Cake",
			"Iced Cafe Mocha",
			"Iced Macchiato",
			"Jellyfish Salad",
			"Kiss on the Lips",
			"Lassi",
			"Leighean Sling",
			"Lemonade",
			"Light Salmon Salad",
			"Lunch Box of Memories",
			"Lutra Cocktail Set",
			"Macchiato",
			"Marshmallow",
			"Mint Chocolate Frappe",
			"Mushroom Canape",
			"Nares Cake Set",
			"Onion Fried Tuna",
			"Orange Juice",
			"Pan's Craft Brew",
			"Peeled Bean Broth",
			"Potato & Egg Salad",
			"Potato Salad",
			"Red Bean Shaved Ice",
			"Red Sunrise",
			"Reuben Sandwich",
			"Roasted Bean Broth",
			"Salmon Sushi",
			"Screwdriver",
			"Seasoned Smelt",
			"Shrimp Bruschetta",
			"Shrimp Burger",
			"Shrimp Dog Food",
			"Strawberry Milk",
			"Strawberry Whipped Cream Crepe",
			"Tamago Sushi",
			"Tara Sausage Sandwich",
			"Tomato Basil Salad",
			"Toro Sushi",
			"Unagi Sushi",
			"Vales Fire",
			"Vegetable Canape",
			"Water-soaked Bean Broth",
			"Weekend Warrior Hotwings & Beer"
	};
	
	private Object[] simmering = {"Steamed Potato"};
	private Object[] baking = {""};
	private Object[] kneading = {"Flour Dough", "Fry Batter"};
	private Object[] boiling = {"Basil Tea","Cheese Fondue", "Starch Syrup"};
	private Object[] noodle = {"Noodle"};
	private Object[] deep_frying = {"Glazed Sweet Potatoes"};
	private Object[] stir_frying = {""};
	
}
