package cookingRecipe;

public class recipeList {
	
	public Object[] mixing = {
			"Afternoon Tea Set",
			"Antioxidant Juice",
			"Apple Juice",
			"Assorted Fruits",
			"Assorted Sashimi",
			"Assorted Sashimi Bibimbap",
			"Bacon and Potato Dog Food",
			"Bacon Burger",
			"Birthday Cake",
			"Blueberry Whipped Cream Crepe",
			"BnR",
			"Bread Crumb",
			"Brifne Rocks",
			"Cacao Chocolate Cake",
			"Cafe Mocha",
			"Camellia Sling",
			"Candied Strawberries",
			"Cappuccino",
			"Catfish Garden Salad",
			"Caviar Canape",
			"Caviar Salad",
			"Celery Salad",
			"Cheeseburger",
			"Cheesy Hot Fries",
			"Chicken Burger",
			"Chocolate Crepe Cake",
			"Chocolate Milk",
			"Chojang",
			"Club Sandwich",
			"Coleslaw",
			"Cookies and Cream Cake",
			"Corn Dog",
			"Corned Abb Neagh Carp and Vegetables",
			"Crepe Cake",
			"Curry Paste",
			"Decadence Platter",
			"Devil's Chocomix",
			"Dog Biscuit",
			"Dragon Flesh Lump",
			"Dreamy Cotton Candy",
			"Ebi Sushi",
			"Egg Caviar",
			"Egg Salad",
			"Egg Sandwich",
			"Espresso Macchiato",
			"Filia Cookie Set",
			"Fruit Salad",
			"Full Kraken Meal",
			"Gastro Burger",
			"Granita",
			"Halloween Wrapped Candy",
			"Halloween Wrapped Cookie",
			"Happy Dessert Time Combo",
			"Hard Cider",
			"Herb Mushroom Salad",
			"Highball",
			"Holiday Cake",
			"Iced Cafe Mocha",
			"Iced Macchiato",
			"Imitation Japari Bun",
			"Jellyfish Salad",
			"Kiss on the Lips",
			"Lassi",
			"Leighean Sling",
			"Lemon Juice",
			"Lemonade",
			"Light Salmon Salad",
			"Lunch Box of Memories",
			"Lutra Cocktail Set",
			"Macchiato",
			"Marshmallow",
			"Mayonnaise",
			"Meat Marinade",
			"Mint Chocolate Frappe",
			"Mixed Vegetables",
			"Mushroom Canape",
			"Nares Cake Set",
			"Onion Fried Tuna",
			"Orange Juice",
			"Pan's Craft Brew",
			"Peeled Bean Broth",
			"Potato & Egg Salad",
			"Potato Salad",
			"Rab's Food",
			"Raw Chopped Kraken",
			"Red Bean Shaved Ice",
			"Red Sunrise",
			"Reuben Sandwich",
			"Roasted Bean Broth",
			"Rose Basil Salad",
			"Rose Pepper Mushroom Stir Fry",
			"Salmon Salad",
			"Salmon Sushi",
			"Screwdriver",
			"Seasoned Smelt",
			"Shrimp Bruschetta",
			"Shrimp Burger",
			"Shrimp Dog Food",
			"Sparkling Water",
			"Spicy Hot Pot",
			"Strawberry Milk",
			"Strawberry Whipped Cream Crepe",
			"Tamago Sushi",
			"Tara Sausage Sandwich",
			"Tomato Basil Salad",
			"Toro Sushi",
			"Unagi Sushi",
			"Vales Fire",
			"Vegetable Canape",
			"Water-soaked Bean",
			"Water-soaked Bean Broth",
			"Weekend Warrior Hotwings & Beer",
			"Yggdrasil Leaf Shrimp Rice",
			"Yggdrasil Vegetable Soup"
	};
	
	public Object[] simmering = {
			"Bean Stuffing",
			"Chicken Soup",
			"Hard-Boiled Egg",
			"Kraken Pulpo",
			"Simmered Beans",
			"Simmered Cabbage",
			"Simmered Chestnuts",
			"Simmered Octopus",
			"Simmered Sweet Potato",
			"Steamed Corn",
			"Steamed Potato",
			"Sweet Pumpkin Puree",
	};
	
	public Object[] baking = {
			"Apple Souffle",
			"Bacon Wrapped Tuna",
			"Baked Potato",
			"Barley Bread",
			"Beef Steak",
			"Belvast Eel Rice Bowl",
			"Black Tea Honey Scone",
			"Boar and Mushroom Skewer",
			"Broiled Brifne Carp",
			"Brownie",
			"Butter Biscuit",
			"Butter Grilled Reef Lobster",
			"Cabbage Pancake",
			"Cannele",
			"Cheese Bread",
			"Cheese Gratin",
			"Chocolate Cake",
			"Chocolate Chip Cookie",
			"Chocolate Souffle",
			"Churrasco",
			"Coconut Cookie",
			"Coconut Pound Cake",
			"Coq Au Vin",
			"Corn Scone",
			"Cornbread",
			"Crazy Chocolate Ball",
			"Crepe",
			"Croffle",
			"Croque Monsieur",
			"Crunchy Mushroom Cookie",
			"Curry Bread",
			"Curry-Roasted Black Sea Bream",
			"Curry-Roasted Red Sea Bream",
			"Dragon T-Bone Steak",
			"Egg & Mayo Toast",
			"Festival Turkey Dish",
			"Flying Fish Crepe",
			"Flying Fish Fin",
			"Fortune Cookie",
			"Fried Dumplings",
			"Fried Egg",
			"Garlic Bread",
			"Gateau Au Chocolat",
			"Giant Star Candy",
			"Gochujang Pork Bulgogi",
			"Grilled Black Dragon Heart",
			"Grilled Catfish",
			"Grilled Corn",
			"Grilled Eel",
			"Grilled Pineapple",
			"Grilled Salted Herring",
			"Grilled Shellfish",
			"Grilled Silk-Striped Marlin",
			"Grilled White Dragon Heart",
			"Gyeran-mari",
			"Halloween Hat Cookie",
			"Halloween Owl Cookie",
			"Halloween Star Cookie",
			"Heartbeat Gateau Au Chocolat",
			"Hotcakes",
			"Jumbo Fried Dumplings",
			"Kikiki Mushroom Cookie",
			"Kraken Skewer",
			"Large Fried Dumplings",
			"Macaroon",
			"Mackerel Steak",
			"Mana Herb Garlic Steak",
			"Milk Bread",
			"Mint Chocolate Cookie",
			"Mushroom Cookie",
			"Mushroom Gratin",
			"Omelet",
			"Pepper Grilled Silk-Striped Marlin",
			"Pineapple Bacon Skewer",
			"Pork Steak",
			"Quiche",
			"Rare Cheesecake",
			"Roasted Bacon",
			"Roasted Bean",
			"Roasted Chicken",
			"Roasted Chicken Wing",
			"Roasted Coffee",
			"Roasted Turkey",
			"S'more",
			"Salt Grilled Sweetfish",
			"Sausage",
			"Schweinshaxe",
			"Scuabtuinne Sucker Skewers",
			"Show-off Pork Steak",
			"Show-off Steak",
			"Sliced Bread",
			"Smoked Sunfish",
			"Strawberry Jam & Toast",
			"Strawberry Shortcake",
			"Striped Marlin Steak",
			"Sturgeon Steak",
			"Sunfish Bone",
			"T-Bone Steak",
			"Taitinn Carp Brochette",
			"Takoyaki",
			"Toast",
			"Toasted Rice Cake",
			"Tofu Steak",
			"Tortilla",
			"Triple Hotcakes",
			"Truffle Omelet"
	};
	
	public Object[] kneading = {
			"Cornbread Dough",
			"Flour Dough",
			"Fry Batter",
			"Shrimp Taming Bait",
			"Taitinn Carp Taming Bait"
	};
	
	public Object[] boiling = {
			
	};
	
	public Object[] noodle = {
			"Assorted Sashimi Noodles",
			"Beltfish Sashimi Noodles",
			"Chicken Chow Mein",
			"Curry Udon",
			"Festive Noodles",
			"Miso Ramen",
			"Noodle",
			"Pad Thai",
			"Peeled Bean Noodles",
			"Roasted Bean Noodles",
			"Seafood Yakisoba",
			"Shio Ramen",
			"Shoyu Ramen",
			"Shrimp Tempura Udon",
			"Somen Noodles",
			"Tofu Noodles A",
			"Tofu Noodles B",
			"Tofu Noodles C",
			"Water-soaked Bean Noodles"
	};
	
	public Object[] deep_frying = {
			
	};
	
	public Object[] stir_frying = {
			
	};
	
}
